[build]
rustflags = ["-Ctarget-cpu=native", "-Cforce-frame-pointers=yes"]

[env]
RUST_LOG = "debug"
RUSTFLAGS = "-Clinker-plugin-lto"

[doc]
browser = "firefox" # browser to use with `cargo doc --open`,

[alias]
t = "test --workspace"
ba = "bench --workspace"
rr = "run --release"
